
openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: Engineering 360 App
    url: http://104.225.216.199:8000/api/doc
info:
  version: "1.0.0"
  title: Engineering 360 API
  description: Taking employee assessments to the moon 🚀
paths:
  # register user
  /auth/register:
    post:
      tags:
        - Authentication
      description: 'Register user'
      operationId: register
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterationInfo'
  # login user
  /auth/login:
    post:
      tags:
        - Authentication
      description: 'Login user'
      operationId: login
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
  # /auth/logout:
  #   post:
  #     tags:
  #       - Authentication
  #     description: 'Logout user'
  #     operationId: logout
  #     responses:
  #       '200':
  #         description: successful operation
  #       '400':
  #         description: Bad request
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/LogoutInfo'
  # /auth/refresh:
  #   post:
  #     tags:
  #       - Authentication
  #     description: 'Refresh token'
  #     operationId: refresh
  #     responses:
  #       '200':
  #         description: successful operation
  #       '400':
  #         description: Bad request
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/Refresh'
  "/auth/password/forgot-password/{email}":
    get:
      tags:
        - Authentication
      description: 'Forgot Password'
      operationId: forgot password
      parameters:
        - name: email
          in: path
          required: true
          type: string
          format: email
          example: "test@mail.com"
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  "/auth/password/reset/{id}/{token}":
    post:
      tags:
        - Authentication
      description: 'Reset Password'
      operationId: reset password
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
          example: "3998502f-f63a-4ba6-b84d-0d85a300dbb4"
        - name: token
          in: path
          required: true
          type: string
          format: uuid
          example: "79b3ac1d2fa1f1f31993"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPassword'
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
        '404':
          description: Not Found
  "/auth/verify/{id}/{token}":
    get:
      tags:
        - Authentication
      description: 'Email verification'
      operationId: verify email
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      parameters:
        - name: id
          in: path
          required: true
          type: string
          example: "3379cfe6-dd11-448f-b3be-47d191a7c724"
        - name: token
          in: path
          required: true
          type: string
          example: "9cc2e4b47a6cf88aa4f7"
  /company/all:
    get:
      tags:
        - Company
      description: 'Fetch all companies'
      operationId: company
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate200'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate401'
  "/company/update/{company_id}":
    put:
      tags:
        - Company
      description: "Update company's info"
      parameters:
        - name: company_id
          in: path
          required: true
          type: company_id
          format: company_id
          example: "9ea09b93-6682-11ed-9941-3863bbb7c6d"
      operationId: update
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate200'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate401'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate400'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyInfo'
  /user/all:
    get:
      tags:
        - Users
      description: 'Fetch Users'
      operationId: users
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
    # fetch user
  "/user/{userId}":
    get:
      tags:
        - Users
      description: 'Fetch User'
      operationId: user
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
    # fetch verified user
  "/user/verified/{userId}":
    get:
      tags:
        - Users
      description: 'Fetch Verified User'
      operationId: verified_user
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
    # update user
  "/user/{userId}/update":
    put:
      tags:
        - Users
      description: 'Update User'
      operationId: update
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      parameters:
        - name: userId
          in: path
          required: true
          example: "3998502f-f63a-4ba6-b84d-0d85a300dbb4"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
    # create employee
  /employee/add:
    post:
      tags:
        - Employee
      description: 'Create employee'
      operationId: employee
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
    # create category
  /category/add:
    post:
      tags:
        - Category
      description: 'Create Category'
      operationId: category
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
    # update category
  /user/categoryId/update:
    put:
      tags:
        - Category
      description: 'Update Category'
      operationId: update
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
    # fetch assessment by organisation
  /assessment/organisationId:
    get:
      tags:
        - Assessment
      description: 'Fetch assessment by organisation'
      operationId: assessment
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assessment'
    # update assessment
  /assessment/assessmentId:
    put:
      tags:
        - Assessment
      description: 'Update assessment'
      operationId: update
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assessment'
    # create assessment
  /assessment/create:
    post:
      tags:
        - Assessment
      description: 'Create Assessment'
      operationId: assessment
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assessment'
    # delete assessment
  /assessment/assessmentId/delete:
    delete:
      tags:
        - Assessment
      description: 'Delete assessment'
      operationId: assessment
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assessment'
    # create question
  /question/add:
    post:
      tags:
        - Question
      description: 'Create question'
      operationId: question
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
    # update question
  /question/questionId/assessmentId/update:
    put:
      tags:
        - Question
      description: 'Update question'
      operationId: update
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
    # create userscore
  /userscore/create:
    post:
      tags:
        - Userscore
      description: 'Create user score'
      operationId: createuserscore
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate200'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate400'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserScoreCreate'
  # get userscore
  /userscore/employee_id/assessment_id:
    get:
      tags:
        - Userscore
      description: 'Get user score'
      operationId: getuserscore
      parameters:
        - name: assessment_id
          in: path
          required: true
          type: assessment_id
          format: assessment_id
          example: "9ea09b93-6682-11ed-9941-3863bbb7c6d"
        - name: employee_id
          in: path
          required: true
          type: employee_id
          format: employee_id
          example: "4ea09b93-6682-11ed-9941-3863bbb7c6e"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate200'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserScoreCreate100'
components:
  schemas:
    ResetPassword:
      type: object
      properties:
        new_password:
          type: string
          format: string
          example: '12345'
          required: true
        type:
          type: string
          format: string
          example: 'organization | employee'
          required: true
    UserUpdate:
      type: object
      properties:
        email:
          type: string
          format: email
          example: 'test@mail.com'
        username:
          type: string
          format: username
          example: 'johny16'
        full_name:
          type: string
          format: string
          example: "John Doe"
    UsersById:
      parameters:
        - name: zoneId
          in: path
          required: true
          schema:
            type: string
    EmailVerificatikon:
      type: object
      
    RegisterationInfo:
      type: object
      properties:
        email:
          type: string
          format: email
          example: 'test@mail.com'
        full_name:
          type: string
          format: string
          example: "John Doe"
          required: true
        username:
          type: string
          format: text
          example: john doe
        password:
          type: string
          format: password
          example: "1234"
    LoginInfo:
      type: object
      properties:
        email:
          type: string
          format: email
          example: 'test@mail.com'
        password:
          type: string
          format: password
          example: "1234"
    UserScoreCreate:
      type: object
      properties:
        assessment_id:
          type: string
          format: assessment_id
          example: '9ea09b93-6682-11ed-9941-3863bbb7c6d'
        employee_id:
          type: string
          format: assessment_id
          example: '9ea09b93-6682-11ed-9941-3863bbb7c6d'
        categories:
          type: array
          format: categories
          example: ['PHP','SQL','REACTJS']
        passed_questions:
          type: array
          format: passed_questions
          example: [20,2,11]
    UserScoreCreate200:
      type: object
      properties:
        status:
          type: boolean
          format: status
          example: true
        message:
          type: string
          format: message
          example: 'successful'
        data:
          type: array
          format: data
          example: [...]
    UserScoreCreate400:
      type: object
      properties:
        status:
          type: string
          format: status
          example: 'error'
        message:
          type: string
          format: message
          example: 'The given data was invalid.'
        errors:
          type: array
          format: errors
          example: [...]
    UserScoreCreate401:
      type: object
      properties:
        message:
          type: string
          format: message
          example: 'Unauthenticated.'
    GetUserscore:
      type: object
      properties:
        assessment_id:
          type: string
          format: assessment_id
          example: '9ea09b93-6682-11ed-9941-3863bbb7c6d'
        employee_id:
          type: string
          format: assessment_id
          example: '9ea09b93-6682-11ed-9941-3863bbb7c6d'
        categories:
          type: array
          format: categories
          example: ['PHP','SQL','REACTJS']
        passed_questions:
          type: array
          format: passed_questions
          example: [20,2,11]
    UpdateCompanyInfo:
      type: object
      properties:
        - name: name
          type: string
          format: name
          example: 'Company Name'
        - org_mail: email
          type: string
          format: email
          example: 'main@company.com'  
    